- tests/connectors/test_jinja.py
- tests/recipes/wrangles/test_main.py
- tests/samples/jinja_generic_template.jinja
- tests/samples/output_template.jinja
- wrangles/connectors/jinja.py
- wrangles/recipe_wrangles/main.py
All tests passed except for S3 (because of log in credentials?)
> Updating Jinja descriptions

- wrangles/recipe_wrangles/create.py
- wrangles/recipe_wrangles/extract.py
- wrangles/recipe_wrangles/format.py
- wrangles/recipe_wrangles/main.py
- wrangles/recipe_wrangles/merge.py
- wrangles/recipe_wrangles/select.py
- wrangles/recipe_wrangles/split.py
> Updating schema

- tests/recipes/test_custom_functions.py
- wrangles/recipe.py
Fixed bugs in recipe.py and added tests to account for these issues
> Kwargs update

- wrangles/recipe_wrangles/select.py
> Removed "output" where output = none #217

- tests/recipes/wrangles/test_extract.py
- tests/recipes/wrangles/test_main.py
- tests/test_wrangles.py
- wrangles/classify.py
- wrangles/extract.py
- wrangles/recipe_wrangles/extract.py
- wrangles/standardize.py
Added model_id to error message for classify, standardize and extract
> Added model_id to wrong type error message

- wrangles/data.py
Added the bit of code below to check for status code 400 and respond with meaningful error message:
```  
if response.status_code == 200:
results = response.json()
elif response.status_code == 400:
raise RuntimeError('Not able to validate access, check wrangle to ensure accessibility')
```
> Added meaningful error message to data.py

- tests/recipes/wrangles/test_main.py
- wrangles/recipe_wrangles/main.py
Added integer functionality to replace
> Replace integers

- tests/recipes/wrangles/test_convert.py
- wrangles/recipe_wrangles/convert.py
Added ability to convert mixed fraction numbers to decimals. Whole numbers separated by a space or a "-"
| input                     | out                        |
|:--------------------------|:---------------------------|
| 1-1/3                     | 0.33                       |
| 1-1/2 cups                | 0.5 cups                   |
| 1 1/2 cups                | 1.5 cups                   |
| 1 1/3                     | 1.33                       |
| not range 1-1/4           | not range 0.25             |
| e.g 1-3/4 - 2-1/2         | e.g 0.75 - 0.5             |
| fraction ranges 1/4 - 1/2 | fraction ranges 0.25 - 0.5 |
> Convert fractions in units to decimals #103

- tests/recipes/test_recipes.py
- wrangles/recipe.py
Updated to a more appropriate error
> Error if invalid recipe -> update error label #300

- tests/recipes/wrangles/test_select.py
- wrangles/config.py
- wrangles/recipe.py
- wrangles/recipe_wrangles/select.py
1. Group BY - to list.
2. Group By - allow where.
3. Fix failing if by and an aggregation contain the same column.
> Group by enhancements

- tests/recipes/wrangles/test_create.py
- wrangles/openai.py
- wrangles/recipe_wrangles/create.py
This is so that create.embeddings can deal with empty values. Should I add the reverse (single space string back to empty string) after the embeddings are generated?
> Added code to replace empty strings with a space

- tests/recipes/wrangles/test_main.py
- wrangles/recipe_wrangles/main.py
- wrangles/standardize.py
Case sensitive has been made snake case here, but just as with Wrangles-Extract-DIY it is still camel case on the server side of things. Let me know if you'd like me to change this.
> Standardize case sensitive

- tests/recipes/wrangles/test_main.py
- tests/recipes/wrangles/test_pandas.py
- tests/recipes/wrangles/test_select.py
- wrangles/recipe_wrangles/main.py
- wrangles/recipe_wrangles/pandas.py
- wrangles/recipe_wrangles/select.py
Here is what this PR covers:
- #314
- #326
- #327
Test cases for all has also been added
> Some Py bugs

- tests/recipes/wrangles/test_main.py
- wrangles/extract.py
- wrangles/format.py
Ensure that letters are not cut off from words
Works with mixed string and list df columns in to_remove
works with numbers that may be in lists in to_remove
> 376 remove words bug

- tests/recipes/wrangles/test_extract.py
- wrangles/extract.py
- wrangles/recipe_wrangles/extract.py
use_spellcheck parameter has also been added here.
> Extract raw

- tests/connectors/test_http.py
- wrangles/connectors/http.py
- Write connector
- OAuth pre-request support
- orient parameter to define JSON structure
- Pass through kwargs
> HTTP Enhancements

- tests/connectors/test_http.py
Test failing due to overriding json key sorting in backend
> Fix failing test due to backend update

- tests/recipes/wrangles/test_merge.py
- wrangles/format.py
This fixes the bug outlined in issue #422
> Concatenate bug

- tests/connectors/test_train.py
- wrangles/connectors/train.py
- wrangles/train.py
I feel like I am missing something here....
> Lookup schema/Tests

- tests/recipes/wrangles/test_extract.py
- tests/recipes/wrangles/test_main.py
- wrangles/recipe_wrangles/main.py
Not sure if this is what  you had in mind. Let me know if it needs any changes.
> Logging memory

- tests/recipes/wrangles/test_main.py
- tests/recipes/wrangles/test_wrangles.py
- wrangles/recipe.py
- wrangles/recipe_wrangles/main.py
- Add fallback for where for columns containing objects and scalar values.
- Ensure where preserves original column order.
> Where enhancements

- .github/workflows/publish-main.yml
- tests/connectors/test_mssql.py
- wrangles/connectors/mssql.py
Make it possible to use Wrangles library with latest Mac OS (M1/M2).
> Macos latest

- tests/recipes/wrangles/test_split.py
- wrangles/recipe_wrangles/split.py
> Split wildcard bug

- tests/recipes/wrangles/test_extract.py
- tests/recipes/wrangles/test_select.py
- wrangles/recipe_wrangles/select.py
Added wrangle to select to measure the lengths of the data in the columns.  Currently supports sequences and collections (default `len()` behavior)
> Length wrangle + test

- wrangles/dataframe.py
Noting that the hints need work to appear in editor.
> Comment out codes_alternative method and add notes
